theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag
repository: MkLHX/boot4modal
social:
  links:
    - https://twitter.com/mklhx
    - https://github.com/mklhx
    - https://www.linkedin.com/in/mickael-lehoux/